### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by AndreaMussmann** [OpenReqEU/dependency-detection#2]
Hi,

I only had the chance to try out the dependency detection service today and the Bad Gateway exception persists (see issue #1). 
Could you please look into it again. 
Thank you!

**Comment by jnerlich** [comment]
@quim-motger Any update here?

**Comment by quim-motger** [comment]
Hi @jnerlich , @AndreaMussmann ,

it has already been reported to ENG , but the error persists. I will push again to see if there is any update or review.

Sorry for the late response. I will let you know once it is available again.

Best regards,

Quim Motger

**Comment by quim-motger** [comment]
Hi @AndreaMussmann ,

I confirm it is available again. 

Best regards,

Quim Motger
